"""add user_fb_id to pages

Revision ID: 736b3ad91e52
Revises: a1b2c3d4e5f6
Create Date: 2026-03-18 07:18:52.001421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '736b3ad91e52'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pages', sa.Column('user_fb_id', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_pages_user_fb_id'), 'pages', ['user_fb_id'], unique=False)
    op.drop_index(op.f('ix_sales_leads_page_status'), table_name='sales_leads')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_sales_leads_page_status'), 'sales_leads', ['page_id', 'status'], unique=False)
    op.drop_index(op.f('ix_pages_user_fb_id'), table_name='pages')
    op.drop_column('pages', 'user_fb_id')
    # ### end Alembic commands ###
